; THIS FILE IS AUTO-GENERATED BY THE ADD-ON!
; We do not recommend you change it unless you know what you are doing.

[default]
host = 127.0.0.1
port = {{ .port }}
password = {{ .password }}
mbox_path = /var/spool/asterisk/voicemail/default/{{ .extension }}/
cache_file = /var/spool/asterisk/transcription.cache
google_key = {{ .api_key }}

# https://github.com/PhracturedBlue/asterisk_mbox_server
