; THIS FILE IS AUTO-GENERATED BY THE ADD-ON!
; We do not recommend you change it unless you know what you are doing.

[general]
enabled=yes
bindaddr=0.0.0.0
bindport=8088
tlsenable=yes
tlsbindaddr=0.0.0.0:8089
tlscertfile={{ .certfile }}
tlsprivatekey={{ .keyfile }}
