; THIS FILE IS AUTO-GENERATED BY THE ADD-ON!
; We do not recommend you change it unless you know what you are doing.

[general]
enabled=yes
bindaddr=[::]
bindport=8088
tlsenable=yes
tlsbindaddr=[::]:8089
tlscertfile={{ .certfile }}
tlsprivatekey={{ .keyfile }}
enablestatic=yes
redirect=/ static/index.html
