build_from:
  aarch64: ghcr.io/hassio-addons/base/aarch64:edge
  amd64: ghcr.io/hassio-addons/base/amd64:edge
  armhf: ghcr.io/hassio-addons/base/armhf:edge
  armv7: ghcr.io/hassio-addons/base/armv7:edge
  i386: ghcr.io/hassio-addons/base/i386:edge